name: 'Publish'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: 'spintaxkt-publish'
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'gradle'
      - name: Publish library to maven central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_projectVersion: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}